<?php
/**
 * Created by PhpStorm.
 * User: dgdev
 * Date: 8/13/19
 * Time: 1:07 PM
 */

namespace HashemiRafsan\GithubApiz\Collections;

use Illuminate\Support\Collection;

class GithubCollection extends Collection
{
//    private $request = [];

//    private  $data = [];

    public function __construct( $items = [] )
    {
//        $this->parseItems($items);
        parent::__construct([(object)(['name' => 'rafsan', 'old' => 10])]);
    }

    public function pluck( $value, $key = null )
    {
        return parent::pluck($value, $key); // TODO: Change the autogenerated stub
    }

    private function parseItems($items)
    {
        foreach($items as $key => $value) {
            $this->{$key} = $value;
        }
    }

    private function checkMethodInScopes($method)
    {
        $path = $this->request->getUri()->getPath();
        $collectionAccessList = include(__DIR__ . '/./CollectionMethodAccess.php');
        return in_array($method, array_get($collectionAccessList, $path));
    }
}
